// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package blog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Blog3Content() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section><h2>The Problem</h2><p>I love reading, but existing epub readers frustrated me. Syncing books between devices was a pain, the interfaces were cluttered, and none of them worked exactly how I wanted.</p></section><section><h2>The Solution: Hatsulingo</h2><p>So I built <a href=\"https://www.hatsulingo.com\">hatsulingo.com</a> - a web-based reading app that focuses on simplicity and sync.</p><p>Key features I wanted:</p><ul><li>Works on any device with a browser</li><li>Automatic sync across devices</li><li>Clean, distraction-free reading interface</li><li>Good typography and reading experience</li></ul></section><section><h2>Technical Details</h2><p>Built with Go on the backend, minimal JavaScript on the frontend. The epub parsing was the trickiest part - those files are basically zip archives with XML content and specific structure requirements.</p><p>Still working on some features, but it's already become my daily reading app. Sometimes the best motivation for building something is that you'll be the primary user.</p></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
