// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package blog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Blog2Content() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section><h2>Go as a Scripting Language</h2><p>Most people think of Python or Bash when they think \"scripting language,\" but I've been using Go for all my scripts lately. Here's why it works so well.</p><p>The compilation step actually makes deployment easier - no dependency management, no \"works on my machine\" issues. Just build once, run anywhere.</p></section><section><h2>My CLI Tools</h2><p>I've built a few tools that I use daily:</p><ul><li><code>vimi</code> - fuzzy finder for files in my home directory</li><li><code>proji</code> - fuzzy finder for project folders</li></ul><p>Both use the same pattern: read directory contents, present fuzzy search interface, output the selected path. Simple but incredibly useful.</p></section><section><h2>Lessons Learned</h2><p>Keep it simple. The best tools do one thing well. Don't over-engineer when 50 lines of Go will solve your problem perfectly.</p></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
