// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package blog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Blog1Content() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section><h2>Beating My Demons</h2><p>I have wanted to write a blog for years but editing articles has always been tough and scary for me for many reasons <a id=\"ref-1\" href=\"#fn-1\">[1]</a>. ; I have like twenty article drafts in my notes that never got to got to see the light of day.</p><p>Last week, I got an advice from a user on twitter that struck with me. He said I should just publish my \"messy drafts\" instead of dreaming of publishing it someday after extensively polishing it. I liked the advice so here I am publishing my every first blog post.</p><p>I plan on releasing more blogs soon now-I have a few ideas in mind. Next one is probably going to be about why I did't like using the frontend framwork Svelte.</p></section><section><details id=\"fn-1\"><summary><strong>[1]</strong> Footnote</summary> The perfectionism, impostor syndrome, inferiority complex combo always kept me from pressing the publish button. <a href=\"#ref-1\">↩</a></details></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
